Here I do some basic math (linear algebra, calculus) to get comfortable with Numpy

In [2]:
import numpy as np
import math as math

A = np.array([[3, 0], [1, 2]])
print(A)
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)


[[3 0]
 [1 2]]
[2. 3.]
[[0.         0.70710678]
 [1.         0.70710678]]


Now consider a matrix:

$$
A=
\begin{bmatrix}
1 & 2\cr
4 & 3
\end{bmatrix}
$$

Compute the eigenvalues for A:

Since eigenvalues λ exist where:

$ det (A-λI) = 0$  or equivalently  $det (λI - A) = 0 $



$$
det(\begin{bmatrix}
λ-1 & -2\cr
-4 & λ-3
\end{bmatrix}) = 0
$$


From the definition for det(A) we have:
$$
\begin{align*}
(λ-1)(λ-3) - 8\\
λ^2 - 3λ - λ + 3 - 8\\
λ^2 - 4λ - 5\\
(λ-5)(λ+1) = 0
\end{align*}
$$
Therefore the eigenvalues for this matrix are:
\begin{align*}
λ = 5, -1
\end{align*}
The eigenvectors of this matrix should be:

$$
\vec{v}_1 = 
\begin{bmatrix}
1/2\cr 1
\end{bmatrix}

\vec{v}_2 = 
\begin{bmatrix}
1\cr-1
\end{bmatrix}
$$


In [3]:
A = np.array([[1, 2], [4, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print("Note the eigenvectors are the span of that vector, so 1/2, 1 is the same as 2, 4")
print(eigenvectors)

B = np.array([[0, 1], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(B)

print(eigenvalues)
print(eigenvectors)



[-1.  5.]
Note the eigenvectors are the span of that vector, so 1/2, 1 is the same as 2, 4
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]
[-0.61803399  1.61803399]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
